title: DONG JUN
description: My Personal Blog
author: dongjun lee
logo: /static/img/avatar.png
github: https://github.com/djlee118
about: Freelance developer

baseurl: "https://djlee118.github.io/"
url: "https://djlee118.github.io/"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
